# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "bento/centos-6.7"
  config.vm.hostname = "c67ap54"

  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.provision :shell, :path => "provision/install.sh"
  config.vm.synced_folder "./sync", "/var/www/html", :mount_options => ["dmode=777", "fmode=666"]

end
